README.pdf: README.md
	pandoc -o README.pdf README.md

reference-organigramme.md.pdf: reference-organigramme.md
	pandoc reference-organigramme.md -o reference-organigramme.md.pdf --highlight-style=tango -f markdown-latex_macros

